version: '3.8'
services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: todo
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

# Networks to be created to facilitate communication between containers
networks:
  app-network:
    driver: bridge

# Volumes to persist database data
volumes:
  dbdata:
    driver: local
